# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b3879f58f37b25a86c090a59b8602f37cdf5b87714b9f659628b6c08a07ab7a83eb54ce925d7b0a444cc9f4c49b2d1161304621b2808746abba757bd9904f56

test:
  secret_key_base: 9a8a9ab11037880a30704c385b03aff5a8474ac03ef53c9216f8b1eee47d9483cbaf50096eb6d0e73027f3b5e84b11a3586ab46451ff15ffb687b900914a378c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
